repos:
  - repo: local
    hooks:
      - id: black
        name: Black code formatter
        entry: black
        language: system
        types: [python]
        args: [".\\python\\"]  #we want to format the python dir
      - id: pytest
        name: Run pytest tests
        entry: pytest
        language: system
        pass_filenames: false
